### ISSUE TITLE
set up your Kanban board

### ISSUE THREAD

**Issue by hafiz1379** [hafiz1379/Catalog-of-my-things#28]
### This is the setup of our work
You can find the GitHub project https://github.com/users/hafiz1379/projects/4/views/1

There are 3 people in this group:

1. https://github.com/hafiz1379
2. https://github.com/JuanDiegoGuerra
3. https://github.com/Rysth

**Comment by ghost** [comment]
Hi Team, 

You can go ahead with your project
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/da75JuW2HHuBNqOHHE/giphy.gif"/>

## Highlights

✅ Tasks are  distributed fairly
✅ Tasks are descriptive
✅ All tasks are assigned


## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by hafiz1379** [comment]
Thank you @frank1738
